services:

  client:
    build:
      context: ./client
    ports:
      - "${CLIENT_PORT_EXTERNAL}:${CLIENT_PORT}"
    environment:
      - REACT_APP_SERVER_API_URL=${SERVER_API_URL}
      - REACT_APP_SERVER_API_PORT=${SERVER_PORT}

  server:
    build:
      context: ./server
    ports:
      - "${SERVER_PORT_EXTERNAL}:${SERVER_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT_EXTERNAL}:${POSTGRES_PORT}"
    # Монтировать том
    volumes:
      - pgdata:/var/lib/postgresql/data

# Том для БД, чтобы сохранить при перезапуске
volumes:
  pgdata:
