apiVersion: v1
kind: ConfigMap
metadata:
  name: 0303-maksimov-evgenii-configmap
  namespace: 0303-maksimov-evgenii
data:
  REACT_APP_SERVER_API_URL: http://localhost
  REACT_APP_SERVER_API_PORT: "5000"
  POSTGRES_USER: user
  POSTGRES_HOST: postgres
  POSTGRES_DB: db
  POSTGRES_PORT: "5432"
  POSTGRES_PORT_EXTERNAL: "5432"
  SERVER_PORT: "5000"
