apiVersion: v1
kind: Pod
metadata:
  name: maksimov-helloworld-k8s
  namespace: 0303-maksimov-evgenii
  labels:
    app: maksimov-helloworld-k8s
spec:
  containers:
    - name: client
      image: 2513009079942350/helloworld-docker-nodejs-client:latest
      ports:
        - containerPort: 3000
          protocol: TCP
      resources:
        requests:
          memory: "12M"
          cpu: "5m"
        limits:
          memory: "24M"
          cpu: "10m"
      env:
      - name: REACT_APP_SERVER_API_URL
        valueFrom:
          configMapKeyRef:
            name: 0303-maksimov-evgenii-configmap
            key: REACT_APP_SERVER_API_URL
      - name: REACT_APP_SERVER_API_PORT
        valueFrom:
          configMapKeyRef:
            name: 0303-maksimov-evgenii-configmap
            key: REACT_APP_SERVER_API_PORT
    - name: server
      image: 2513009079942350/helloworld-docker-nodejs-server:latest
      ports:
        - containerPort: 5000
          protocol: TCP
      resources:
        requests:
          memory: "48M"
          cpu: "13m"
        limits:
          memory: "96M"
          cpu: "25m"
      env:
      - name: POSTGRES_USER
        valueFrom:
          configMapKeyRef:
            name: 0303-maksimov-evgenii-configmap
            key: POSTGRES_USER
      - name: POSTGRES_HOST
        valueFrom:
          configMapKeyRef:
            name: 0303-maksimov-evgenii-configmap
            key: POSTGRES_HOST
      - name: POSTGRES_DB
        valueFrom:
          configMapKeyRef:
            name: 0303-maksimov-evgenii-configmap
            key: POSTGRES_DB
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: 0303-maksimov-evgenii-secret
            key: POSTGRES_PASSWORD
      - name: POSTGRES_PORT
        valueFrom:
          configMapKeyRef:
            name: 0303-maksimov-evgenii-configmap
            key: POSTGRES_PORT
      - name: SERVER_PORT
        valueFrom:
          configMapKeyRef:
            name: 0303-maksimov-evgenii-configmap
            key: SERVER_PORT
    - name: postgres
      image: postgres:alpine
      ports:
        - containerPort: 5432
          protocol: TCP
      resources:
        requests:
          memory: "32M"
          cpu: "5m"
        limits:
          memory: "64M"
          cpu: "10m"
      env:
      - name: POSTGRES_USER
        valueFrom:
          configMapKeyRef:
            name: 0303-maksimov-evgenii-configmap
            key: POSTGRES_USER
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: 0303-maksimov-evgenii-secret
            key: POSTGRES_PASSWORD
      - name: POSTGRES_DB
        valueFrom:
          configMapKeyRef:
            name: 0303-maksimov-evgenii-configmap
            key: POSTGRES_DB
